spring:
  application:
    name: lg-commerce
  datasource:
    url: jdbc:mysql://${DB_HOSTNAME}:${DB_PORT}/${DB_NAME}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      data-source-properties:
        useServerPrepStmts: true
        cacheServerConfiguration: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        cacheResultSetMetadata: true
        cachePrepStmts: true
        rewriteBatchedStatements: true
        elideSetAutoCommits: true
        useLocalSessionState: true
        maintainTimeStats: false
      idle-timeout: 300000
      pool-name: ConnPool
      maximum-pool-size: 10
      connection-timeout: 50000
      max-lifetime: 1800000
      connection-test-query: select 1
      minimum-idle: 10
    type: com.zaxxer.hikari.HikariDataSource
  redis:
   host: ${REDIS_HOST}
   port: ${REDIS_PORT}
  mail:
   host: ${EMAIL_SERVER_HOST}
   username: ${SUPPORT_EMAIL}
   password: ${APP_PASSWORD}
   port: ${EMAIL_SERVER_PORT}
   properties:
    mail:
     smtp:
      auth: true
      starttls:
       enable: true


  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        current_session_context_class: thread
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration # Đường dẫn chứa file migration
    baseline-on-migrate: true        # Đặt baseline nếu DB chưa được versioned
    validate-on-migrate: true        # Kiểm tra tính hợp lệ trước khi chạy migration
    clean-on-validation-error: false # Không tự động xóa dữ liệu khi có lỗi validation

server:
  shutdown: graceful
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 4096
  port: 6969
lg-commerce:
 app:
  jwtExpirationMs: ${JWT_EXPIRATION}
  refreshExpiration: ${REFRESH_EXPIRATION}
  jwtSecret: ${JWT_SECRET}
  otpLiveTime: ${OTP_LIVE_TIME}